-- CreateTable
CREATE TABLE "GlobalSession" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "activeSessionId" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
